name: moor_db_viewer
description: A package to view your moor database in your own app with filtering and without the need of exporting your db file.
version: 4.3.0
homepage: https://github.com/vanlooverenkoen/moor_db_viewer

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  # moor: ^4.4.0
  moor_flutter: ^4.0.0
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
